name: Create Pull Request for OpenAPI update
on:
  push:
    branches:
    - action/marblerun/update-swagger
    - feat/publish-swagger #debug

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Update OpenAPI specification"
        github_token: ${{ secrets.GITHUB_TOKEN }}
